version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env  # ← .envを読み込む
  db:
    image: postgres:15
    container_name: mydb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OYAPewoYlrTwCHMGeowncDSttHhEInfc
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
